// Demo data for the Wing Girl app prototype
export const demoProfiles = [
  {
    id: 1,
    name: "Marcus",
    age: 27,
    city: "Washington, DC",
    bio: "Architect by day, vinyl collector by night. I cook better than your favorite restaurant and I'm not afraid to prove it.",
    greenFlags: ["Plans actual dates", "Remembers details", "Great listener", "Consistent texter"],
    redFlags: [],
    datingIntent: "Long-term relationship",
    personality: ["Ambitious", "Romantic", "Thoughtful"],
    career: "Architect",
    education: "Howard University",
    energy: "Ambitious / Warm / Intentional",
    tagline: "The Greatest",
    wingGirlNote: "He's the friend who actually plans dates and shows up early. Marcus once drove 3 hours just to bring me soup when I was sick. That's the energy.",
    wingGirlName: "Keisha",
    wingGirlRelation: "sister",
    songTitle: "Best Part",
    songArtist: "Daniel Caesar ft. H.E.R.",
    photoUrls: [
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&h=1000&fit=crop",
      "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1488161628813-04466f872be2?w=600&h=800&fit=crop",
    ],
    badge: "Sister Approved",
    approved: true,
    active: true,
  },
  {
    id: 2,
    name: "Jordan",
    age: 25,
    city: "New York, NY",
    bio: "Software engineer who reads poetry. I'll debug your heart and your code. Weekend farmer's market regular — I make a mean shakshuka.",
    greenFlags: ["Emotionally intelligent", "Financially responsible", "Family-oriented", "Great cook"],
    redFlags: [],
    datingIntent: "Something meaningful",
    personality: ["Creative", "Grounded", "Witty"],
    career: "Software Engineer",
    education: "MIT",
    energy: "Creative / Soft / Funny",
    tagline: "IT GIRL's Guy",
    wingGirlNote: "Jordan is the kind of guy who remembers your coffee order after hearing it once. My best friend for 8 years — he's the real deal.",
    wingGirlName: "Destiny",
    wingGirlRelation: "friend",
    songTitle: "Come Through",
    songArtist: "Summer Walker",
    photoUrls: [
      "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=800&h=1000&fit=crop",
      "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1531384441138-2736e62e0919?w=600&h=800&fit=crop",
    ],
    badge: "Friend Vouched",
    approved: true,
    active: true,
  },
  {
    id: 3,
    name: "Elijah",
    age: 29,
    city: "Atlanta, GA",
    bio: "Producer & creative director. My love language is acts of service and building things that matter. I still call my grandma every Sunday.",
    greenFlags: ["Protective not possessive", "Communicator", "Driven", "Gentleman"],
    redFlags: [],
    datingIntent: "Long-term relationship",
    personality: ["Charismatic", "Loyal", "Visionary"],
    career: "Creative Director",
    education: "Morehouse College",
    energy: "Magnetic / Driven / Gentle",
    tagline: "Mean Girl's Brother",
    wingGirlNote: "My brother is the most loyal person I know. He once canceled a work trip to be at my graduation. Any woman who gets him is winning.",
    wingGirlName: "Nia",
    wingGirlRelation: "sister",
    songTitle: "Adorn",
    songArtist: "Miguel",
    photoUrls: [
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800&h=1000&fit=crop",
      "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1506277886164-e25aa3f4ef7f?w=600&h=800&fit=crop",
    ],
    badge: "Sister Approved",
    approved: true,
    active: true,
  },
  {
    id: 4,
    name: "Xavier",
    age: 26,
    city: "Chicago, IL",
    bio: "Finance guy who doesn't make it his whole personality. I journal, I meditate, and I can two-step at any function. Your mom will love me.",
    greenFlags: ["Self-aware", "Adventurous", "Supportive", "Well-dressed"],
    redFlags: [],
    datingIntent: "Partnership",
    personality: ["Balanced", "Fun", "Genuine"],
    career: "Financial Analyst",
    education: "Northwestern University",
    energy: "Smooth / Grounded / Playful",
    tagline: "Swamp Princess's Catch",
    wingGirlNote: "Xavier is my cousin and he's genuinely one of the best men I know. He brings flowers for no reason and actually reads the books he talks about.",
    wingGirlName: "Aisha",
    wingGirlRelation: "cousin",
    songTitle: "SNooze",
    songArtist: "SZA",
    photoUrls: [
      "https://images.unsplash.com/photo-1504257432389-52343af06ae3?w=800&h=1000&fit=crop",
      "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1552374196-c4e7ffc6e126?w=600&h=800&fit=crop",
    ],
    badge: "Cousin Certified",
    approved: true,
    active: true,
  },
  {
    id: 5,
    name: "Darius",
    age: 28,
    city: "Los Angeles, CA",
    bio: "Photographer with a law degree. I see the beauty in everything and I'm not afraid to say how I feel. Let me take your portrait.",
    greenFlags: ["Expressive", "Reliable", "Culturally aware", "Patient"],
    redFlags: [],
    datingIntent: "Long-term relationship",
    personality: ["Artistic", "Deep", "Warm"],
    career: "Photographer / Attorney",
    education: "UCLA",
    energy: "Artistic / Deep / Present",
    tagline: "The Dark Horse",
    wingGirlNote: "Darius is the coworker everyone trusts. He's thoughtful, he's genuine, and he gives the best advice. Whoever dates him is lucky.",
    wingGirlName: "Jasmine",
    wingGirlRelation: "coworker",
    songTitle: "Pink + White",
    songArtist: "Frank Ocean",
    photoUrls: [
      "https://images.unsplash.com/photo-1548372290-8d01b6c8e78c?w=800&h=1000&fit=crop",
      "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1534030347209-467a5b0ad3e6?w=600&h=800&fit=crop",
    ],
    badge: "Friend Vouched",
    approved: true,
    active: true,
  },
];

export const demoCurrentUser = {
  id: 100,
  email: "demo@winggirl.app",
  name: "Zara",
  role: "woman_dater" as const,
  verified: true,
  avatarUrl: null,
  points: 240,
};

export const demoMatches = [
  {
    id: 1,
    profile: demoProfiles[0],
    lastMessage: "Hey Zara, I'd love to get coffee this weekend if you're free?",
    lastMessageTime: "2 min ago",
    unread: true,
  },
  {
    id: 2,
    profile: demoProfiles[2],
    lastMessage: "That playlist you mentioned sounds amazing",
    lastMessageTime: "1 hr ago",
    unread: false,
  },
];

export const demoMessages = [
  { id: 1, senderId: 1, content: "Hey Zara! Thanks for the like. I saw you're into architecture too — what's your favorite building in DC?", time: "Yesterday 8:32 PM" },
  { id: 2, senderId: 100, content: "The National Museum of African American History! The design is incredible. Have you been?", time: "Yesterday 9:15 PM" },
  { id: 3, senderId: 1, content: "Yes! David Adjaye is a genius. The corona form is inspired by Yoruba art — the way light filters through the bronze lattice is something else.", time: "Yesterday 9:22 PM" },
  { id: 4, senderId: 100, content: "Okay you really know your stuff. Impressed.", time: "Yesterday 9:25 PM" },
  { id: 5, senderId: 1, content: "Hey Zara, I'd love to get coffee this weekend if you're free?", time: "Today 6:45 PM" },
];
